In [3]:
import pandas as pd
import sqlalchemy
from db_config import get_engine

In [17]:
test_df = pd.read_parquet('gold//yearly_tariffs.parquet')
test_df.head()

,identifier,container_number,description_sequence_number,harmonized_number,harmonized_value,harmonized_weight_combined,harmonized_weight_kg,year
0,2018010128,TGHU0209174,1,36.0,3280.0,16430.000 Kilograms,16430.0,2018
1,2018010169,SUDU8579238,1,8479.0,NaN,5254.000 Kilograms,5254.0,2018
2,2018010170,SUDU8784361,1,93.0,2170.0,10880.000 Kilograms,10880.0,2018
3,20180101111,NC,1,8320.0,2.0,1300.000 Kilograms,1300.0,2018
4,20180101112,NC,1,8320.0,420.0,2130.000 Kilograms,2130.0,2018

In [13]:
gold_df = pd.read_parquet('gold//tariff_gold.parquet')
engine = get_engine()

def test_connection(engine):
    try: 
        with engine.connect() as connection: 
            print("Connection successful")
    except Exception as e:
        print(f"Connection failed: {e}")

def load_data_to_sql(df, table_name, engine):
    try:
        df.to_sql(table_name, con=engine, if_exists='replace', index=False)
        print(f"Data loaded successfully into {table_name}")
    except Exception as e:
        print(f"Failed to load data: {e}")

In [14]:
print(gold_df.shape)

(7024194, 4)

In [15]:
test_connection(engine)
load_data_to_sql(gold_df, 'yearly_tariffs', engine)
verify_df = pd.read_sql("SELECT TOP 5 * FROM yearly_tariffs", con=engine)
print(verify_df)

Connection successful
Data loaded successfully into yearly_tariffs
      identifier  total_harmonized_weight_kg harmonized_weight_unit  \
0  2018010818496                     23368.0    23368.000 Kilograms
1  2018010818497                     23898.0    23898.000 Kilograms
2  2018010818498                      9429.0     9429.000 Kilograms
3  2018010818510                     18900.0    18900.000 Kilograms
4  2018010818516                     16000.0    16000.000 Kilograms

   total_tariff_lines
0                   1
1                   1
2                   1
3                   1
4                   1

In [16]:
verify_df.head(100)

,identifier,total_harmonized_weight_kg,harmonized_weight_unit,total_tariff_lines
0,2018010818496,23368.0,23368.000 Kilograms,1
1,2018010818497,23898.0,23898.000 Kilograms,1
2,2018010818498,9429.0,9429.000 Kilograms,1
3,2018010818510,18900.0,18900.000 Kilograms,1
4,2018010818516,16000.0,16000.000 Kilograms,1